### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by Dr-WeiAL** [LNatit/EnchantmentSort#1]
[crash-2022-12-16_21.48.24-client.txt](https://github.com/LNatit/EnchantmentSort/files/10246261/crash-2022-12-16_21.48.24-client.txt)
似乎是和传说工具提示冲突(

**Comment by LNatit** [comment]
我在[mcmod](https://www.mcmod.cn/download/8442.html)上传了一个补丁版本，你可以试试是否还会出现崩溃。

**Comment by Dr-WeiAL** [comment]
好的，不过这个问题不确定是怎么触发的，短时间内可能试不出来

**Comment by LNatit** [comment]
> 好的，不过这个问题不确定是怎么触发的，短时间内可能试不出来

大概是因为原版或其他模组某些配置情况下会隐藏部分附魔条目的显示导致的问题，我加了个判断条件，现在应该不会再出现了（

**Comment by Dr-WeiAL** [comment]
@LNatit 刷屏了(
![image](https://user-images.githubusercontent.com/47446553/208232919-81fe5cf4-b1f1-4c19-8578-94cf1432c913.png)

**Comment by LNatit** [comment]
> @LNatit 刷屏了( ![image](https://user-images.githubusercontent.com/47446553/208232919-81fe5cf4-b1f1-4c19-8578-94cf1432c913.png)

这。。。不然我回头在配置文件里加个选项禁用警告？
（话说gh这issue关了以后的新评论就不会提示了？

**Comment by LNatit** [comment]
> @LNatit 刷屏了( ![image](https://user-images.githubusercontent.com/47446553/208232919-81fe5cf4-b1f1-4c19-8578-94cf1432c913.png)
（不然我回头在配置文件里加个选项禁用警告？
（话说gh这issue关了以后的新评论就不会提示了？

**Comment by qznfbnj** [comment]
~~刷屏占空间？就用[Delogger](https://www.curseforge.com/minecraft/mc-mods/delogger)~~

**Comment by LNatit** [comment]
如果还有这种情况可以在配置文件里开兼容模式
（~~鸽了五个月终于把新版本写出来了~~）
