### ISSUE TITLE
EnchSort Rendering overlay error: java.lang.NoSuchFieldError: f_122825_

### ISSUE THREAD

**Issue by Ariostraza** [LNatit/EnchantmentSort#2]
Minecraft 1.19.3
Forge 44.1.5

Crash report: [[JustPasteIt Link]](https://justpaste.it/cetq0)

Probably incompatible with some other mod im using, i have obscure tooltips which you might notice when reading my mod list. Everything else is chinese to me so i cant help you beyond that.

**Comment by LNatit** [comment]
Well, it seems that I took it for granted that mods in 1.19.2 will work well in 1.19.3.
I will update a version for 1.19.3 later on. (I'll leave another comment below once it's uploaded)
BTW I'm sorry for the delay, I didn't check my mailbox recently.

**Comment by LNatit** [comment]
I just uploaded the file, you will see it on curseforge after review.
Thx for feedback:)
