### ISSUE TITLE
附魔排序的1.1.5版本使1.16.5版本加载错误

### ISSUE THREAD

**Issue by XiFengXF** [LNatit/EnchantmentSort#4]
![image](https://github.com/LNatit/EnchantmentSort/assets/97110012/7204299b-0462-43f3-9acb-87656b72983c)
只加附魔排序模组，在加载期间也会造成此问题

**Comment by LNatit** [comment]
我傻逼了，1.16.5没有JarInJar
现在改用shadow打包了，cf应该很快就能审核通过，可以先去mcmod上下载最新版本，不过暂时还不能确定mod的功能有没有受到影响（应该是没问题的，可以抽空测一下）
