### ISSUE TITLE
Note for 1.20.x version

### ISSUE THREAD

**Issue by SiverDX** [LNatit/EnchantmentSort#6]
If you plan on releasing a version for 1.20.x and keep Apotheosis compat you will need to change this:

https://github.com/LNatit/EnchantmentSort/blob/a1d8b7266f0fdc111e12562a2fe2f55ec0c2185d/src/main/java/com/lnatit/enchsort/ApotheosisSupport.java#L25

`shadows` is now `dev.shadowsoffire`

**Comment by LNatit** [comment]
Git it!
